---
grails:
    profile: web
    codegen:
        defaultPackage: apikey
    config:
        locations:
            - file:/data/apikey/config/apikey-config.properties
            - file:/data/apikey/config/apikey-config.yml
            - file:/data/apikey/config/apikey-config.groovy
    spring:
        transactionManagement:
            proxies: false
    gorm:
        # Whether to autowire entities. 
        # Disabled by default for performance reasons.
        autowire: false         
        reactor:
            # Whether to translate GORM events into Reactor events
            # Disabled by default for performance reasons
            events: false
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
spring:
    main:
        banner-mode: "off"
    groovy:
        template:
            check-template-location: false
    devtools:
      restart:
        additional-exclude:
          - '*.gsp'
          - '**/*.gsp'
          - '*.gson'
          - '**/*.gson'
          - 'logback.groovy'
          - '*.properties'
    data:
      redis:
        repositories:
          enabled: false
    session:
        store-type: none
        disable-redis-config-action: false
        grails:
          mutableAttributes:
            - SYNCHRONIZER_TOKENS_HOLDER
server:
  forward-headers-strategy: native
  tomcat:
    remoteip:
      protocol-header: x-forwarded-proto
      port-header: x-forwarded-port
      remote-ip-header: x-forwarded-for
      protocol-header-https-value: https

---
spring:
  flyway:
      enabled: true
      baselineOnMigrate: true
      baselineVersion: 1
      table: schema_version
---
grails:
    mime:
        disable:
            accept:
                header:
                    userAgents:
        types:
            all: '*/*'
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            form: application/x-www-form-urlencoded
            html:
              - text/html
              - application/xhtml+xml
            js: text/javascript
            json:
              - application/json
              - text/json
            multipartForm: multipart/form-data
            pdf: application/pdf
            rss: application/rss+xml
            text: text/plain
            hal:
              - application/hal+json
              - application/hal+xml
            xml:
              - text/xml
              - application/xml
    urlmapping:
        cache:
            maxsize: 1000
    controllers:
        defaultScope: singleton
    converters:
        encoding: UTF-8
    views:
        default:
            codec: html
        gsp:
            encoding: UTF-8
            htmlcodec: xml
            codecs:
                expression: html
                scriptlets: html
                taglib: none
                staticparts: none
    cache:
        enabled: true
        ehcache:
            cacheManagerName: 'apikey-cache-manager'
            ehcacheXmlLocation: 'classpath:apikey-ehcache.xml'
            reloadable: false
endpoints:
    jmx:
        unique-names: true
---
skin:
    layout: "ala-main"
    fluidLayout: false
    orgNameLong: "Atlas of Living Australia"
    orgNameShort: "ALA"
userDetails:
  url: https://auth.ala.org.au/userdetails

security:
    cas:
        uriFilterPattern: ["/testAuth","/upload"]
        authenticateOnlyIfLoggedInFilterPattern: ["/*"]
    filterOrder: 0
    basic:
        enabled: true
        authorizeMode: role
        realm: ALA APIKey
        path:
          - /status/**
    user:
      name: admin
      password: secret
      role:
        - ACTUATOR
endpoints:
    enabled: false
    sensitive: true
    jmx:
        unique-names: true
    cors:
        allow-credentials: true
        allowed-methods:
          - GET
          - POST
          - DELETE
          - PUT
        allowed-headers: "*"
        allowed-origins: "*"
management:
    context-path: /status
    health:
      redis:
        enabled: false # set to true for HA environments
    security:
        enabled: true
        roles:
          - ACTUATOR
spring:
    boot:
        admin:
            client:
                enabled: false
                service-base-url: ${serverURL}
                metadata:
                    user:
                        name: ${security.user.name}
                        password: ${security.user.password}

environments:
    development:
        security:
            cas:
                appServerName: http://devt.ala.org.au:8080
        grails:
            logging:
                jul:
                    usebridge: true
    test:
        security:
                cas:
                    appServerName: http://devt.ala.org.au:8080
    production:
        security:
                cas:
                    appServerName: http://auth.ala.org.au
        grails:
            logging:
                jul:
                    usebridge: false
---
hibernate:
    cache:
        queries: false
        use_second_level_cache: false
        use_query_cache: false

dataSource:
    pooled: true
    jmxExport: true
    type: "com.zaxxer.hikari.HikariDataSource"
#    properties:


# environment specific settings
environments:
    development:
        dataSource:
            dbCreate: validate
            driverClassName: com.mysql.cj.jdbc.Driver
            url: "jdbc:mysql://localhost:3306/apikey?useSSL=false"
    test:
        dataSource:
            dbCreate: update
            driverClassName: org.h2.Driver
            username: sa
            password: ""
            url: "jdbc:h2:mem:testDb;LOCK_TIMEOUT=10000"
    production:
        dataSource:
            dbCreate: validate
            driverClassName: com.mysql.cj.jdbc.Driver
